# Generated by Django 2.0.2 on 2018-07-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='countries',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='genericNameFr',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='nameFr',
            field=models.CharField(max_length=200),
        ),
    ]
