# Generated by Django 2.0.2 on 2018-09-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20180906_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image_url',
        ),
        migrations.AddField(
            model_name='food',
            name='image_link',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
